# Generated by Django 3.2.7 on 2021-09-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210909_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondgasstation',
            name='fuel',
        ),
        migrations.AddField(
            model_name='secondgasstation',
            name='fuel',
            field=models.ManyToManyField(to='api.Fuel'),
        ),
    ]
