# Generated by Django 3.2.7 on 2021-09-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210909_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstgasstation',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
    ]
