# Generated by Django 3.2.7 on 2021-09-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_firstgasstation_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstgasstation',
            name='images',
        ),
        migrations.AddField(
            model_name='firstgasstation',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='api.Image'),
        ),
        migrations.RemoveField(
            model_name='firstgasstation',
            name='services',
        ),
        migrations.AddField(
            model_name='firstgasstation',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='api.Service'),
        ),
    ]
