# Generated by Django 3.2.7 on 2021-09-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210909_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasstation',
            name='fuel',
        ),
        migrations.AddField(
            model_name='gasstation',
            name='fuel',
            field=models.ManyToManyField(to='api.Fuel'),
        ),
    ]
