# Generated by Django 3.2.7 on 2021-09-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210909_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasstation',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.Image'),
        ),
        migrations.AlterField(
            model_name='gasstation',
            name='services',
            field=models.ManyToManyField(blank=True, to='api.Service'),
        ),
    ]
