# Generated by Django 3.2.7 on 2021-09-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210909_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasstation',
            name='fuel',
            field=models.ManyToManyField(blank=True, to='api.Fuel'),
        ),
    ]
