# Generated by Django 3.2.7 on 2021-09-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_gasstation_fuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasstation',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='gasstation',
            name='images',
        ),
        migrations.RemoveField(
            model_name='gasstation',
            name='services',
        ),
        migrations.AddField(
            model_name='fuel',
            name='station',
            field=models.ManyToManyField(blank=True, to='api.GasStation'),
        ),
        migrations.AddField(
            model_name='image',
            name='station',
            field=models.ManyToManyField(blank=True, to='api.GasStation'),
        ),
        migrations.AddField(
            model_name='service',
            name='station',
            field=models.ManyToManyField(blank=True, to='api.GasStation'),
        ),
    ]
