# Generated by Django 3.2.7 on 2021-09-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210909_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='station',
        ),
        migrations.RemoveField(
            model_name='image',
            name='station',
        ),
        migrations.RemoveField(
            model_name='service',
            name='station',
        ),
        migrations.AddField(
            model_name='gasstation',
            name='fuel',
            field=models.ManyToManyField(blank=True, related_name='stations', to='api.Fuel'),
        ),
        migrations.AddField(
            model_name='gasstation',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='stations', to='api.Image'),
        ),
        migrations.AddField(
            model_name='gasstation',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='stations', to='api.Service'),
        ),
    ]
